CRUD_Сlients API/Models/Pager/Pager.cs
namespace CRUD_Сlients_API.Models.Pager
{
    public class Pager
    {
        public int TotalItems { get; private set; } 
        public int CurrentPage { get; private set; } // номер текущей страницы
        public int PageSize { get; private set; } // кол-во объектов на странице
        public int TotalPages { get; private set; }
        public int StartPage { get; private set; }
        public int EndPage { get; private set;}

        public Pager()
        { 
        }

        public Pager(int totalItems, int page, int pageSize = 10)
        {
            int totalPages = (int)Math.Ceiling((decimal)totalItems / (decimal)pageSize);
            int currentPage = page;

            int startPage = currentPage - 5;
            int endPage = currentPage + 4;

            if (startPage <= 0)
            {
                endPage = endPage - (startPage - 1);
                startPage = 1;
            }
            if (endPage > totalPages)
            {
                endPage = totalPages;
                if(endPage>10)
                {
                    startPage = endPage - 9;
                }
            }
            TotalItems = totalItems;
            CurrentPage = currentPage;
            PageSize= pageSize;
            TotalPages = totalPages;
            StartPage = startPage;
            EndPage = endPage;
        }
    }

}

CRUD_Сlients API/Controllers/ClientController.cs
using CRUD_Сlients_API.Services;
using CRUD_Сlients_API.Models;
using Microsoft.AspNetCore.Mvc;
using CRUD_Сlients_API.Models.Client;
using System.Text;
using System;
using System.Collections.Generic;
using CRUD_Сlients_API.Models.Pager;
using Microsoft.AspNetCore.Mvc.Infrastructure;

namespace CRUD_Сlients_API.Controllers
{
    public class ClientController : Controller
    {

        private readonly ClientApiService _servcie;
        private static ClientRequestViewModel requestGetClients = new ClientRequestViewModel();
        private static ClientInfoViewModel currClient = new ClientInfoViewModel();
        public ClientController(ClientApiService service)
        {
            _servcie = service;
            _servcie.ErrorHandler += ServerErrorException;
        }

        [HttpGet]
        public IActionResult Index(int pg=1)
        {
            if (requestGetClients.data.Count>0)
            {
                const int pageSize = 5;
                if (pg < 1)
                    pg = 1;
                int recsCount = requestGetClients.data.Count;
                var pager = new Pager(recsCount, pg, pageSize);
                int recSkip = (pg - 1) * pageSize;
                var data = requestGetClients.data.Skip(recSkip).Take(pager.PageSize).ToList();
                ViewBag.Pager = pager;
                requestGetClients.dataPager = data;

            }
            return View("Index", requestGetClients);
        }


        [HttpPost]
        public async Task<IActionResult> GetClients(ClientRequestViewModel form)
        {

            await _servcie.GetClinets((Response<ClientResponseModel> result) =>
            {
                requestGetClients = new ClientRequestViewModel
                {
                    request = form.request,
                    data = result.response.data.ToList()
                };
            }, form.request);
            return Index();
        }

        [HttpGet]
        public IActionResult CreateClient()
        {
            return RedirectToPage("/Create");
        }

        [HttpPost]
        public async Task<IActionResult> CreateClient(ClientInfoViewModel client)
        {
            await _servcie.CreateClient(() =>
            {

            }, client);

            return Index();
        }

        [HttpGet]
        public async Task<IActionResult> GetClinet(Guid id)
        {
            ClientInfoViewModel client = new ClientInfoViewModel();
            await _servcie.GetClinet((ClientInfoViewModel _client) =>
            {
                currClient = _client;
            }, id);
            return View("Show", currClient);
        }

        [HttpGet]
        public IActionResult Edit()
        {
            return View("Edit", currClient);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateClient(ClientInfoViewModel client)
        {
            await _servcie.UpdateClinet(() =>
            {

            }, client);
            
            return RedirectToAction("IndexRefresh");
        }

        [HttpGet]
        public async Task<IActionResult> DeleteClient(Guid id)
        {
            await _servcie.DeleteClinet(() => 
            { 
            
            },id);
            return RedirectToAction("IndexRefresh");
        }

        [HttpGet]
        public async Task<IActionResult> IndexRefresh()
        {
            await _servcie.GetClinets((Response<ClientResponseModel> result) =>
            {
                requestGetClients = new ClientRequestViewModel
                {
                    request = requestGetClients.request,
                    data = result.response.data.ToList()
                };
            }, requestGetClients.request);
            return Index();
        }

        public void ServerErrorException(object obj, string message)
        {
            ViewBag.success = false;
            ViewBag.errorMessage = message != null? message: "Ошибка сервера";
        }
        
    }
}

CRUD_Сlients API/Views/Shared/_Alert.cshtml
@{

}
@if (ViewBag.success != null)
{
    @if (!ViewBag.success)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>@ViewBag.errorMessage</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }
    else if (ViewBag.success)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>@ViewBag.successMessage</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

    }
}

CRUD_Сlients API/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD_Сlients_API</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUD_Сlients_API.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CRUD_Сlients_API</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Index</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Alert" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CRUD_Сlients_API - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

 
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CRUD_Сlients API/Views/Shared/_Pager.cshtml
@model CRUD_Сlients_API.Models.Pager.Pager

<div class="container">

    @if (Model.TotalPages > 0)
    {
        <ul class="pagination justify-content-end">
            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Client" asp-action="Index">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="Client" asp-action="Index" asp-route-pg="@(Model.CurrentPage-1)">Previous</a>
                </li>

            }
            @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
            {
                <li class="page-item @(pge ==Model.CurrentPage ? "active": "")">
                    <a class="page-link" asp-controller="Client" asp-action="Index" asp-route-pg="@pge">@pge</a>
                </li>

            }
            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Client" asp-action="Index" asp-route-pg="@(Model.CurrentPage+1)">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="Client" asp-action="Index" asp-route-pg="@(Model.TotalPages)">Last</a>
                </li>

            }
        </ul>
    }
</div>